// namespaces
#define Grafikus_könyvtár Graph_lib
#define alap std
#define Számos_könyvtár Numeric_lib

// types
#define Pont Point
#define Egyszerű_ablak Simple_window
#define Tengely Axis
#define Funkció Function
#define Sokszög Polygon
#define Téglalap Rectangle
#define Kép Image
#define Kör Circle
#define Elipszis Ellipse
#define Szín Color
#define Szöveg Text
#define Vonal_stílus Line_style
#define Betűtípus Font
#define Jel Mark
#define Cím Address
#define Vonalak Lines
#define Gomb Button
#define Vonalak_ablak Lines_window
#define Ablak Window
#define Be_doboz In_box
#define Ki_doboz Out_box
#define Menü Menu
#define Mátrix Matrix
// std types
#define kifolyam ostream
#define befolyam istream
#define kiszövegfolyam ostringstream
#define kivétel exception
#define szám int
#define logikai bool
#define üresség void
#define szöveg string
#define futóidő_hiba runtime_error
#define vektor vector
// should this be "dupla" instead?
#define tört double
#define karakter char
#define rövid short
#define hosszú long
#define lebegő float
#define tömb array
#define lista list
#define iterátor iterator
#define térkép map
#define pár pair
#define összead plus
#define kivon minus
#define beffolyam ifstream
#define komplex complex

// colors
#define piros red
#define kék blue
#define zöld green
#define sárga yellow
#define fehér white
#define fekete black
#define türkiz cyan
#define sötét_piros dark_red
#define sötét_zöld dark_green
#define sötét_sárga dark_yellow
#define sötét_kék dark_blue
#define sötét_magenta dark_magenta
#define sötét_türkiz dark_cyan

// line styles
#define tömör solid
#define csík dash
#define pont dot
#define csíkpont dashdot
#define csíkpontpont dashdotdot

// functions
#define várj_a_gombra wait_for_button
#define címke_beállít set_label
#define szín_beállít set_color
#define hozzáad add
#define betűtípus_beáll set_font
#define betűméret_beáll set_font_size
#define mozgat move
#define csatlakoztat attach
#define kitöltő_szín_beállít set_fill_color
#define stílus_beállít set_style
#define maszk_beállít set_mask
#define elrejt hide
#define mutat show
#define újrarajzol redraw
#define szerez_szám get_int
#define rak put
#define referencia_hozzá reference_to
//std functions
#define fő main
#define szöv str
#define mi what
#define nyom_hátra push_back
#define méret size
#define véletlen rand
#define talál find
#define minden_egyes for_each
#define kezd begin
#define vég end
#define távolság distance
#define tisztít clear
#define felhalmoz accumulate
#define belső_termék inner_product
#define megfordít reverse
#define hátra_szúró back_inserter
#define sorbarendez sort
#define eltávolít_ha remove_if
#define kitöröl erase
#define mérete sizeof

// fields
#define cki cout
#define cbe cin
#define chiba cerr
#define sorv endl
#define függőleges vertical
#define első first
#define második second

// keywords
#define próbál try
#define elkap catch
#define visszaad return
#define használ using
#define névűr namespace
#define igaz true
#define hamis false
#define mert for
#define miközben while
#define osztály class
#define nyilvános public
#define privát private
#define védelmezett protected
#define virtuális virtual
#define ha if
#define különben else
#define dob throw
#define állandó const
#define állandókifejez constexpr
#define kezelő operator
#define eltör break
#define struktúra struct
#define új new
#define minta template
#define típusnév typename